# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    app.wallpaper.bing_downloader:
        class: AppBundle\Wallpaper\BingDownloader
        arguments: ['@httplug.client']

    app.wallpaper.url_provider:
        class: AppBundle\Wallpaper\UrlProvider
